# project.yml — Control Plane Configuration
#
# Generated/updated by the Setup Wizard.
# Manual edits are welcome.

version: 1
name: devops-control-plane
description: A general-purpose project control plane for DevOps automation
repository: github.com/cyberpunk042/devops-control-plane
owners:
  - name: "Cyberpunk 042"
    github: "cyberpunk042"
domains:
- library
- ops
- docs
environments:
- default: true
  description: New development
  name: development
- default: false
  description: Production environment
  name: production
modules:
- description: Domain models, services, and engine
  domain: library
  name: core
  path: src/core
  stack: python-lib
- description: Tool bindings for git, docker, etc.
  domain: library
  name: adapters
  path: src/adapters
  stack: python-lib
- description: Click-based CLI interface
  domain: ops
  name: cli
  path: src/ui/cli
  stack: python-cli
- description: Flask admin web interface
  domain: ops
  name: web
  path: src/ui/web
  stack: python-flask
- description: Project documentation
  domain: docs
  name: docs
  path: docs
  stack: markdown
content_folders:
- docs
external:
  ci: github-actions
pages:
  segments:
  - name: docs
    source: docs
    builder: docusaurus
    path: /docs
    auto: true
    config: {}
