# Rust stack — detection and capabilities
name: rust
icon: "🦀"
description: "Rust project"
detail: >
  Rust is a systems programming language focused on safety, speed, and
  concurrency. It prevents memory bugs at compile time with its ownership
  model and has no garbage collector.
  
  Technical: Rust project detected via Cargo.toml. Provides build, lint
  (clippy), format (rustfmt), and test capabilities.
domain: service

detection:
  files_any_of:
    - Cargo.toml
  files_all_of: []
  content_contains: {}

requires:
  - adapter: shell
    min_version: ""

capabilities:
  - name: install
    adapter: shell
    command: "cargo fetch"
    description: "Download dependencies"
  - name: lint
    adapter: shell
    command: "cargo clippy -- -D warnings"
    description: "Run Clippy linter"
  - name: format
    adapter: shell
    command: "cargo fmt"
    description: "Format code"
  - name: test
    adapter: shell
    command: "cargo test"
    description: "Run tests"
  - name: build
    adapter: shell
    command: "cargo build"
    description: "Build project"
  - name: check
    adapter: shell
    command: "cargo check"
    description: "Type-check without building"
