# Protobuf / gRPC stack — buf or raw protoc
name: protobuf
icon: "📡"
description: "Protocol Buffers / gRPC"
detail: >
  Protocol Buffers (protobuf) provide a language-neutral, platform-neutral
  mechanism for serializing structured data. gRPC uses protobuf for efficient
  service-to-service communication.
  
  Technical: Protocol Buffers / gRPC project detected via .proto files.
  Provides generate and lint capabilities.
domain: service

detection:
  files_any_of:
    - buf.yaml
    - buf.gen.yaml
    - buf.work.yaml
  files_all_of: []
  content_contains: {}

requires:
  - adapter: shell
    min_version: ""

capabilities:
  - name: lint
    adapter: shell
    command: "buf lint"
    description: "Lint proto files"
  - name: format
    adapter: shell
    command: "buf format -w"
    description: "Format proto files"
  - name: build
    adapter: shell
    command: "buf generate"
    description: "Generate code from protos"
  - name: test
    adapter: shell
    command: "buf breaking --against '.git#branch=main'"
    description: "Check breaking changes"
