"""Integration tests for core.

Tests that verify core works correctly within the larger project.
Auto-generated by DevOps Control Plane.
"""
from __future__ import annotations


def test_core_importable():
    """Verify core is importable from the project root."""
    import src.core  # noqa: F401

