"""Integration tests for web.

Tests that verify web works correctly within the larger project.
Auto-generated by DevOps Control Plane.
"""
from __future__ import annotations


def test_web_importable():
    """Verify web is importable from the project root."""
    import src.ui.web  # noqa: F401

