"""Integration tests for cli.

Tests that verify cli works correctly within the larger project.
Auto-generated by DevOps Control Plane.
"""
from __future__ import annotations


def test_cli_importable():
    """Verify cli is importable from the project root."""
    import src.ui.cli  # noqa: F401

