"""Compatibility tests for cli.

Auto-generated by DevOps Control Plane.
Verifies imports, public API, version compatibility, and dependency availability.
Regenerate with: module upgrade → "Generate compatibility tests"
"""
from __future__ import annotations

import importlib
import sys

import pytest


# ── 1. Import Verification ──────────────────────────────────────
# Every .py file in the module should be importable without errors.

_MODULE_PATHS = [
    "src.ui.cli",
    "src.ui.cli.audit",
    "src.ui.cli.audit.install",
    "src.ui.cli.audit.plans",
    "src.ui.cli.audit.resume",
    "src.ui.cli.backup",
    "src.ui.cli.ci",
    "src.ui.cli.content",
    "src.ui.cli.content.crypto",
    "src.ui.cli.content.optimize",
    "src.ui.cli.content.release",
    "src.ui.cli.dns",
    "src.ui.cli.docker",
    "src.ui.cli.docker.actions",
    "src.ui.cli.docker.detect",
    "src.ui.cli.docker.generate",
    "src.ui.cli.docker.observe",
    "src.ui.cli.docs",
    "src.ui.cli.git",
    "src.ui.cli.git.core",
    "src.ui.cli.git.github",
    "src.ui.cli.infra",
    "src.ui.cli.infra.detect",
    "src.ui.cli.infra.env",
    "src.ui.cli.infra.iac",
    "src.ui.cli.k8s",
    "src.ui.cli.k8s.detect",
    "src.ui.cli.k8s.generate",
    "src.ui.cli.k8s.observe",
    "src.ui.cli.metrics",
    "src.ui.cli.packages",
    "src.ui.cli.pages",
    "src.ui.cli.pages.build",
    "src.ui.cli.pages.info",
    "src.ui.cli.pages.segments",
    "src.ui.cli.posture",
    "src.ui.cli.quality",
    "src.ui.cli.scripts",
    "src.ui.cli.scripts.history",
    "src.ui.cli.scripts.info",
    "src.ui.cli.scripts.list",
    "src.ui.cli.scripts.run",
    "src.ui.cli.secrets",
    "src.ui.cli.secrets.crud",
    "src.ui.cli.secrets.envs",
    "src.ui.cli.secrets.status",
    "src.ui.cli.security",
    "src.ui.cli.security.detect",
    "src.ui.cli.security.generate",
    "src.ui.cli.security.observe",
]


@pytest.mark.parametrize("module_path", _MODULE_PATHS)
def test_module_importable(module_path):
    """Verify each module file can be imported."""
    importlib.import_module(module_path)


# ── 3. Version Compatibility ────────────────────────────────────
# The module claims Python >=3.8 support.

def test_python_version_floor():
    """Verify we are running on at least the declared minimum."""
    assert sys.version_info >= (3, 8), (
        f"Module requires Python >=3.8, running on {sys.version_info}"
    )


# ── 4. Dependency Imports ────────────────────────────────────────
# All declared dependencies should be importable.

_DECLARED_DEPS = [
    "click",
    "pytest",
]


@pytest.mark.parametrize("dep", _DECLARED_DEPS)
def test_dependency_importable(dep):
    """Verify each declared dependency can be imported."""
    try:
        importlib.import_module(dep)
    except ImportError:
        pytest.skip(f"{dep} not installed in this environment")
