# Java (Gradle) stack — detects build.gradle or build.gradle.kts
name: java-gradle
icon: "☕"
description: "Java/Kotlin project (Gradle)"
detail: >
  A Java or Kotlin project using Gradle for build management. Gradle offers
  flexible, scriptable builds with incremental compilation and build caching.
  
  Technical: Java/Kotlin Gradle project detected via build.gradle or
  build.gradle.kts. Provides build, test, and clean capabilities.
domain: service

detection:
  files_any_of:
    - build.gradle
    - build.gradle.kts
  files_all_of: []
  content_contains: {}

requires:
  - adapter: shell
    min_version: ""

capabilities:
  - name: install
    adapter: shell
    command: "./gradlew dependencies"
    description: "Resolve dependencies"
  - name: lint
    adapter: shell
    command: "./gradlew check"
    description: "Run checks"
  - name: test
    adapter: shell
    command: "./gradlew test"
    description: "Run tests"
  - name: build
    adapter: shell
    command: "./gradlew build -x test"
    description: "Build project"
  - name: clean
    adapter: shell
    command: "./gradlew clean"
    description: "Clean build artifacts"
