"""Compatibility tests for core.

Auto-generated by DevOps Control Plane.
Verifies imports, public API, version compatibility, and dependency availability.
Regenerate with: module upgrade → "Generate compatibility tests"
"""
from __future__ import annotations

import importlib
import sys

import pytest


# ── 1. Import Verification ──────────────────────────────────────
# Every .py file in the module should be importable without errors.

_MODULE_PATHS = [
    "src.core",
    "src.core.config",
    "src.core.config.loader",
    "src.core.config.stack_loader",
    "src.core.context",
    "src.core.data",
    "src.core.data.script_templates.audit",
    "src.core.data.script_templates.audit.code_hygiene",
    "src.core.data.script_templates.audit.data_layer_leaks",
    "src.core.data.script_templates.audit.doc_validator",
    "src.core.data.script_templates.audit.init_analyzer",
    "src.core.data.script_templates.audit.layer_analyzer",
    "src.core.data.script_templates.audit.route_analyzer",
    "src.core.data.script_templates.audit.route_quality",
    "src.core.data.script_templates.generators",
    "src.core.data.script_templates.generators.api_catalog",
    "src.core.data.script_templates.generators.api_route_scanner",
    "src.core.data.script_templates.generators.class_diagrams",
    "src.core.data.script_templates.lib",
    "src.core.data.script_templates.lib.code_analyzer",
    "src.core.data.script_templates.lib.file_discovery",
    "src.core.data.script_templates.lib.graph_builder",
    "src.core.data.script_templates.lib.mermaid_generator",
    "src.core.data.script_templates.lib.report_formatter",
    "src.core.engine",
    "src.core.engine.executor",
    "src.core.engine.operation_context",
    "src.core.models",
    "src.core.models.action",
    "src.core.models.module",
    "src.core.models.project",
    "src.core.models.stack",
    "src.core.models.state",
    "src.core.models.template",
    "src.core.observability",
    "src.core.observability.console",
    "src.core.observability.health",
    "src.core.observability.logging_config",
    "src.core.observability.metrics",
    "src.core.persistence",
    "src.core.persistence.audit",
    "src.core.persistence.state_file",
    "src.core.reliability",
    "src.core.reliability.circuit_breaker",
    "src.core.reliability.retry_queue",
    "src.core.security",
    "src.core.services",
    "src.core.services.artifacts",
    "src.core.services.artifacts.builders",
    "src.core.services.artifacts.builders.base",
]


@pytest.mark.parametrize("module_path", _MODULE_PATHS)
def test_module_importable(module_path):
    """Verify each module file can be imported."""
    importlib.import_module(module_path)


# ── 3. Version Compatibility ────────────────────────────────────
# The module claims Python >=3.8 support.

def test_python_version_floor():
    """Verify we are running on at least the declared minimum."""
    assert sys.version_info >= (3, 8), (
        f"Module requires Python >=3.8, running on {sys.version_info}"
    )


# ── 4. Dependency Imports ────────────────────────────────────────
# All declared dependencies should be importable.

_DECLARED_DEPS = [
    "flask",
    "pydantic",
    "pytest",
]


@pytest.mark.parametrize("dep", _DECLARED_DEPS)
def test_dependency_importable(dep):
    """Verify each declared dependency can be imported."""
    try:
        importlib.import_module(dep)
    except ImportError:
        pytest.skip(f"{dep} not installed in this environment")
