# Node.js stack — detection and capabilities
name: node
icon: "📦"
description: "Node.js project"
detail: >
  Node.js is a JavaScript runtime built on V8 that enables server-side
  programming. It excels at I/O-heavy workloads, real-time applications, and
  full-stack JavaScript development.
  
  Technical: Node.js project detected via package.json. Provides install
  (npm), lint (eslint), format (prettier), test, and build capabilities.
  Flavored stacks like node-express or node-nextjs add framework-specific
  dev/serve commands.
domain: service

detection:
  files_any_of:
    - package.json
  files_all_of: []
  content_contains: {}

requires:
  - adapter: node
    min_version: "18"

capabilities:
  - name: install
    adapter: shell
    command: "npm install"
    description: "Install dependencies"
  - name: lint
    adapter: shell
    command: "npm run lint"
    description: "Run linter"
  - name: format
    adapter: shell
    command: "npm run format"
    description: "Format code"
  - name: test
    adapter: shell
    command: "npm test"
    description: "Run tests"
  - name: build
    adapter: shell
    command: "npm run build"
    description: "Build project"
