"""
Integration test: Helm generate → detect round-trip (0.4.close).

Proves that charts generated by k8s_helm_generate.generate_helm_chart()
are correctly found and parsed by k8s_detect._detect_helm_charts().
"""

from __future__ import annotations

from pathlib import Path

import pytest

from src.core.services.k8s_helm_generate import generate_helm_chart
from src.core.services.k8s_detect import _detect_helm_charts

pytestmark = pytest.mark.integration


# ═══════════════════════════════════════════════════════════════════
#  Helpers
# ═══════════════════════════════════════════════════════════════════


def _svc(name: str = "api", image: str = "myapp:v1.2.3", **kw) -> dict:
    return {"name": name, "image": image, "port": 8080, "replicas": 2, **kw}


def _gen_and_detect(data: dict, tmp_path: Path) -> list[dict]:
    """Generate chart then run detection on the output directory."""
    generate_helm_chart(data, tmp_path)
    return _detect_helm_charts(tmp_path)


# ═══════════════════════════════════════════════════════════════════
#  Round-trip: generate → detect
# ═══════════════════════════════════════════════════════════════════


class TestHelmRoundTrip:
    """Generated charts are correctly detected."""

    def test_basic_roundtrip(self, tmp_path: Path):
        """Generate chart → detect finds it with correct name/version."""
        data = {
            "helm_chart": True,
            "_services": [_svc()],
        }
        charts = _gen_and_detect(data, tmp_path)
        assert len(charts) == 1
        chart = charts[0]
        assert chart["name"] == "api"
        assert chart["version"] == "0.1.0"

    def test_description_roundtrip(self, tmp_path: Path):
        """Project description flows through generate → detect."""
        data = {
            "helm_chart": True,
            "_services": [_svc()],
            "_project_description": "My awesome API",
        }
        charts = _gen_and_detect(data, tmp_path)
        assert charts[0]["description"] == "My awesome API"

    def test_has_values_flag(self, tmp_path: Path):
        """Generated chart has values.yaml → detected has_values=True."""
        data = {
            "helm_chart": True,
            "_services": [_svc()],
        }
        charts = _gen_and_detect(data, tmp_path)
        assert charts[0]["has_values"] is True

    def test_has_templates_flag(self, tmp_path: Path):
        """Generated chart has templates/ → detected has_templates=True."""
        data = {
            "helm_chart": True,
            "_services": [_svc()],
        }
        charts = _gen_and_detect(data, tmp_path)
        assert charts[0]["has_templates"] is True

    def test_app_version_roundtrip(self, tmp_path: Path):
        """Image tag → appVersion in Chart.yaml → detected."""
        data = {
            "helm_chart": True,
            "_services": [_svc(image="myapp:v2.0.0")],
        }
        charts = _gen_and_detect(data, tmp_path)
        assert charts[0]["app_version"] == "v2.0.0"

    def test_env_values_files_roundtrip(self, tmp_path: Path):
        """Per-env values files generated → detected in env_values_files."""
        data = {
            "helm_chart": True,
            "_services": [_svc()],
            "environments": ["dev", "staging", "prod"],
        }
        charts = _gen_and_detect(data, tmp_path)
        env_files = charts[0].get("env_values_files", [])
        assert "values-dev.yaml" in env_files
        assert "values-staging.yaml" in env_files
        assert "values-prod.yaml" in env_files

    def test_chart_type_roundtrip(self, tmp_path: Path):
        """Generated chart type=application → detected."""
        data = {
            "helm_chart": True,
            "_services": [_svc()],
        }
        charts = _gen_and_detect(data, tmp_path)
        assert charts[0]["type"] == "application"
