# Zig stack — modern systems language
name: zig
icon: "⚡"
description: "Zig project"
detail: >
  Zig is a modern systems programming language that aims to replace C with
  better safety, readability, and tooling. It features comptime evaluation and
  a built-in build system.
  
  Technical: Zig project detected via build.zig. Provides build, test, and run
  capabilities using the Zig build system.
domain: service

detection:
  files_any_of:
    - build.zig
    - build.zig.zon
  files_all_of: []
  content_contains: {}

requires:
  - adapter: shell
    min_version: ""

capabilities:
  - name: build
    adapter: shell
    command: "zig build"
    description: "Build project"
  - name: test
    adapter: shell
    command: "zig build test"
    description: "Run tests"
  - name: format
    adapter: shell
    command: "zig fmt ."
    description: "Format code"
  - name: clean
    adapter: shell
    command: "rm -rf zig-out zig-cache .zig-cache"
    description: "Clean build artifacts"
