"""
Wizard setup — infrastructure scaffolding: Docker, K8s, Terraform, Pages.

Generates Dockerfiles, docker-compose, K8s manifests, Helm charts,
Terraform configs, and Pages segments.

Channel-independent: no Flask or HTTP dependency.
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def setup_pages(root: Path, data: dict) -> dict:
    """Initialize Pages segments from detected content folders.

    Supported data keys:
        auto_init  – bool, run init_pages_from_project to create segments
    """
    from src.core.services import devops_cache

    results: list[str] = []

    if data.get("auto_init"):
        from src.core.services.pages_discovery import init_pages_from_project

        init_result = init_pages_from_project(root)
        added = init_result.get("added", [])
        details = init_result.get("details", [])

        for d in details:
            results.append(
                f"Segment '{d['name']}' → {d['builder']}"
                + (f" ({d['suggestion']})" if d.get("suggestion") else "")
            )

        if not added:
            results.append("No new segments to initialize")

    if not results:
        return {"ok": True, "message": "No pages actions requested", "results": []}

    devops_cache.record_event(
        root,
        label="📄 Pages Setup",
        summary=f"Pages configured: {', '.join(results) or 'no changes'}",
        detail={"results": results},
        card="wizard",
        action="configured",
        target="pages",
    )

    return {
        "ok": True,
        "message": f"Pages initialized ({len(results)} segment(s))",
        "results": results,
    }


def setup_docker(root: Path, data: dict) -> dict:
    """Generate Dockerfile and optional docker-compose.yml / .dockerignore.

    Supported data keys:
        base_image, workdir, install_cmd, port, cmd, overwrite, compose,
        dockerignore, registry, image_name, build_args.
    """
    from src.core.services import devops_cache

    base_image = data.get("base_image", "python:3.12-slim")
    workdir = data.get("workdir", "/app")
    install_cmd = data.get("install_cmd", "pip install -e .")
    port = data.get("port", "8080")
    cmd = data.get("cmd", "python -m src")
    overwrite = data.get("overwrite", False)
    compose = data.get("compose", False)
    dockerignore = data.get("dockerignore", False)
    registry = data.get("registry", None)
    image_name = data.get("image_name", None)
    build_args = data.get("build_args", None)

    files_created: list[str] = []

    cmd_parts = cmd.split()
    cmd_json = ", ".join(f'"{p}"' for p in cmd_parts)

    dest = root / "Dockerfile"
    if dest.exists() and not overwrite:
        return {
            "ok": False,
            "error": "Dockerfile already exists. Check 'Overwrite' to replace.",
        }

    # Build ARG directives if build_args provided
    arg_lines = ""
    if isinstance(build_args, dict) and build_args:
        arg_lines = "\n".join(f"ARG {k}" for k in build_args) + "\n\n"

    dest.write_text(
        f"FROM {base_image}\n\n"
        f"{arg_lines}"
        f"WORKDIR {workdir}\n"
        f"COPY . .\n"
        f"RUN pip install --no-cache-dir --upgrade pip && \\\n"
        f"    {install_cmd}\n\n"
        f"EXPOSE {port}\n"
        f"CMD [{cmd_json}]\n"
    )
    files_created.append("Dockerfile")

    if compose:
        compose_dest = root / "docker-compose.yml"
        if not compose_dest.exists() or overwrite:
            name = root.name.replace(" ", "-").lower()
            compose_dest.write_text(
                f'version: "3.9"\n'
                f"services:\n"
                f"  app:\n"
                f"    build: .\n"
                f"    container_name: {name}\n"
                f"    ports:\n"
                f'      - "{port}:{port}"\n'
                f"    volumes:\n"
                f"      - .:{workdir}\n"
                f"    restart: unless-stopped\n"
            )
            files_created.append("docker-compose.yml")

    if dockerignore:
        ignore_dest = root / ".dockerignore"
        if not ignore_dest.exists() or overwrite:
            ignore_dest.write_text(
                "# Generated by DevOps Control Plane\n"
                ".git\n"
                ".gitignore\n"
                "__pycache__\n"
                "*.pyc\n"
                ".venv\n"
                "venv\n"
                "node_modules\n"
                ".env\n"
                ".env.*\n"
                "*.log\n"
                "Dockerfile\n"
                "docker-compose*.yml\n"
                ".dockerignore\n"
            )
            files_created.append(".dockerignore")

    devops_cache.record_event(
        root,
        label="🐳 Docker Setup",
        summary=f"Docker configured ({', '.join(files_created)})",
        detail={"files_created": files_created},
        card="wizard",
        action="configured",
        target="docker",
    )

    result: dict = {
        "ok": True,
        "message": "Docker configuration generated",
        "files_created": files_created,
    }

    # Echo back optional config for downstream use
    if registry:
        result["registry"] = registry
    if image_name:
        result["image_name"] = image_name
    if build_args:
        result["build_args"] = build_args

    return result


def setup_k8s(root: Path, data: dict) -> dict:
    """Generate Kubernetes manifests from wizard state."""
    from src.core.services import devops_cache
    from src.core.services.k8s_ops import (
        wizard_state_to_resources,
        generate_k8s_wizard,
        _generate_skaffold,
    )
    from src.core.services.k8s_helm_generate import generate_helm_chart

    files_created: list[str] = []

    # Translate wizard state → flat resource list
    resources = wizard_state_to_resources(data)

    # Generate manifests (returns {ok, files} or {error})
    result = generate_k8s_wizard(root, resources)
    if result.get("error"):
        return {"ok": False, "error": result["error"]}

    # Collect all files to write (manifests + optional skaffold)
    all_files = list(result.get("files", []))

    # Generate skaffold.yaml if checkbox was checked
    skaffold_file = _generate_skaffold(data, all_files)
    if skaffold_file:
        all_files.append(skaffold_file)

    # Write generated files to disk
    skipped: list[str] = []
    for f in all_files:
        fpath = root / f["path"]
        if fpath.exists() and not f.get("overwrite", True):
            skipped.append(f["path"])
            continue
        fpath.parent.mkdir(parents=True, exist_ok=True)
        fpath.write_text(f["content"])
        files_created.append(f["path"])

    # Generate Helm chart if toggle was checked (writes directly to disk)
    helm_result = generate_helm_chart(data, root)
    helm_files = helm_result.get("files", [])
    files_created.extend(helm_files)

    resp: dict = {
        "ok": True,
        "message": f"Kubernetes manifests generated ({len(files_created)} files)",
        "files_created": files_created,
    }
    if skipped:
        resp["files_skipped"] = skipped
        resp["message"] += f", {len(skipped)} skipped (already exist)"

    devops_cache.record_event(
        root,
        label="☸️ K8s Setup",
        summary=(
            f"K8s manifests generated ({len(files_created)} files"
            + (f", {len(skipped)} skipped" if skipped else "")
            + ")"
        ),
        detail={"files_created": files_created, "files_skipped": skipped},
        card="wizard",
        action="configured",
        target="kubernetes",
    )

    return resp


def setup_terraform(root: Path, data: dict) -> dict:
    """Generate Terraform scaffolding via generate_terraform().

    Delegates to the generator to produce main.tf, variables.tf,
    outputs.tf, and .gitignore — then writes them to disk.
    """
    from src.core.services import devops_cache
    from src.core.services.terraform_generate import generate_terraform

    provider = data.get("provider", "aws")
    backend = data.get("backend", "local")
    project_name = data.get("project_name", root.name)
    overwrite = data.get("overwrite", False)

    tf_dir = root / "terraform"
    tf_main = tf_dir / "main.tf"

    if tf_main.exists() and not overwrite:
        return {
            "ok": False,
            "error": "Terraform config exists. Check 'Overwrite' to replace.",
        }

    # Delegate to the generator
    gen_result = generate_terraform(
        root,
        provider,
        backend=backend,
        project_name=project_name,
    )
    if "error" in gen_result:
        return {"ok": False, "error": gen_result["error"]}

    # Write generated files to disk
    files_created: list[str] = []
    for f in gen_result["files"]:
        path = root / f["path"]
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(f["content"])
        files_created.append(f["path"])

    devops_cache.record_event(
        root,
        label="🏗️ Terraform Setup",
        summary=f"Terraform config generated (provider={provider}, backend={backend})",
        detail={"files_created": files_created, "provider": provider, "backend": backend},
        card="wizard",
        action="configured",
        target="terraform",
    )

    return {
        "ok": True,
        "message": "Terraform configuration generated",
        "files_created": files_created,
    }
