"""
Wizard setup — DNS & CDN configuration generation.

Generates zone files, records.json, CNAME, proxy configs
(nginx / caddy / traefik / cloudflared), K8s Ingress + cert-manager,
and Terraform DNS/CDN/SSL modules.

Channel-independent: no Flask or HTTP dependency.
"""

from __future__ import annotations

import json as _json
import logging
import textwrap as _textwrap
from pathlib import Path

logger = logging.getLogger(__name__)


def setup_dns(root: Path, data: dict) -> dict:
    """Generate DNS & CDN configuration files from wizard state.

    Delegates to ``dns_cdn_ops.generate_dns_records`` for DNS record and zone
    file generation, then writes additional output files (records.json,
    README.md, CNAME, CDN/proxy configs).

    Supported data keys:
        domain         – primary domain (required)
        subdomains     – list[str] of extra subdomains
        dns_provider   – "cloudflare" | "route53" | … | "manual"
        cdn_provider   – "none" | "cloudflare" | "cloudfront" | …
        ssl            – "managed" | "letsencrypt" | "certmanager" | "manual"
        mail           – "none" | "google" | "protonmail" | …
        spf            – bool, include SPF record
        dmarc          – bool, include DMARC record
        ingress        – "nginx" | "traefik" | "alb" (K8s)
        certmanager    – bool, generate cert-manager manifests
        k8s_routes     – list[{host, service, port}]
        proxy          – "nginx" | "caddy" | "traefik" | "cloudflared" (Docker)
        upstream       – upstream URL for proxy
        pages_cname    – bool, generate GitHub Pages CNAME
        tf_dns         – bool, generate Terraform dns.tf
        tf_cdn         – bool, generate Terraform cdn.tf
        tf_ssl         – bool, generate Terraform ssl.tf
        overwrite      – bool, replace existing files
    """
    from src.core.services import devops_cache
    from src.core.services.dns_cdn_ops import generate_dns_records

    domain = data.get("domain", "").strip()
    if not domain:
        return {"ok": False, "error": "Domain is required."}

    subdomains: list[str] = data.get("subdomains", [])
    dns_provider = data.get("dns_provider", "manual")
    cdn_provider = data.get("cdn_provider", "none")
    ssl_strategy = data.get("ssl", "managed")
    mail = data.get("mail", "none")
    spf = data.get("spf", True)
    dmarc = data.get("dmarc", True)
    overwrite = data.get("overwrite", False)

    # ── Guard: dns/ directory exists check ──────────────────────────
    dns_dir = root / "dns"
    zone_path = dns_dir / f"{domain}.zone"
    if zone_path.exists() and not overwrite:
        return {
            "ok": False,
            "error": "DNS config already exists. Check 'Overwrite' to replace.",
        }

    # ── 1. Generate DNS records via existing generator ──────────────
    gen_result = generate_dns_records(
        domain,
        mail_provider=mail if mail != "none" else "",
        include_spf=spf,
        include_dmarc=dmarc,
    )
    if not gen_result.get("ok"):
        return {"ok": False, "error": gen_result.get("error", "DNS generation failed")}

    records = gen_result["records"]
    zone_content = gen_result["zone_file"]

    # Add subdomain A/CNAME records
    for sub in subdomains:
        sub_name = sub if "." in sub else sub
        records.append({
            "type": "CNAME",
            "name": sub_name,
            "value": f"{domain}.",
            "ttl": 300,
        })
        # Append to zone file
        fqdn = f"{sub_name}.{domain}." if not sub_name.endswith(".") else sub_name
        zone_content += f"{fqdn:<30} {300:<8} IN  {'CNAME':<8} {domain}.\n"

    # ── 2. Build file list ──────────────────────────────────────────
    files: list[dict] = []

    # Zone file
    files.append({
        "path": f"dns/{domain}.zone",
        "content": zone_content,
    })

    # Machine-readable records
    records_json = _json.dumps(
        {"domain": domain, "subdomains": subdomains, "records": records},
        indent=2,
    )
    files.append({
        "path": "dns/records.json",
        "content": records_json + "\n",
    })

    # README
    sub_section = ""
    if subdomains:
        sub_list = "\n".join(f"- `{s}.{domain}`" if "." not in s else f"- `{s}`" for s in subdomains)
        sub_section = f"\n## Subdomains\n\n{sub_list}\n"

    readme = _textwrap.dedent(f"""\
        # DNS & CDN Configuration — {domain}

        Generated by DevOps Control Plane.

        ## Domain

        - **Primary**: `{domain}`
        - **DNS Provider**: {dns_provider}
        - **CDN**: {cdn_provider}
        - **SSL**: {ssl_strategy}
        {sub_section}
        ## Files

        | File | Description |
        |------|-------------|
        | `{domain}.zone` | BIND-format zone file |
        | `records.json` | Machine-readable DNS records |
        | `README.md` | This file |

        ## Record Summary

        | Type | Name | Value |
        |------|------|-------|
    """).lstrip()

    for r in records:
        readme += f"    | {r['type']} | {r['name']} | {r['value']} |\n"

    readme += "\n"
    files.append({"path": "dns/README.md", "content": readme})

    # ── 3. CNAME for GitHub Pages ──────────────────────────────────
    if data.get("pages_cname"):
        files.append({
            "path": "CNAME",
            "content": domain + "\n",
        })

    # ── 4. CDN / Proxy config ──────────────────────────────────────
    proxy = data.get("proxy", "")
    upstream = data.get("upstream", "http://localhost:3000")

    if proxy == "nginx" or cdn_provider == "nginx":
        all_hosts = [domain] + [
            f"{s}.{domain}" if "." not in s else s for s in subdomains
        ]
        server_names = " ".join(all_hosts)
        nginx_conf = _textwrap.dedent(f"""\
            # Nginx reverse proxy — generated by DevOps Control Plane
            server {{
                listen 80;
                server_name {server_names};

                location / {{
                    proxy_pass {upstream};
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }}
            }}
        """)
        files.append({"path": "cdn/nginx.conf", "content": nginx_conf})

    elif proxy == "caddy" or cdn_provider == "caddy":
        all_hosts = [domain] + [
            f"{s}.{domain}" if "." not in s else s for s in subdomains
        ]
        caddy_conf = f"# Caddyfile — generated by DevOps Control Plane\n"
        for host in all_hosts:
            caddy_conf += f"\n{host} {{\n    reverse_proxy {upstream}\n}}\n"
        files.append({"path": "cdn/Caddyfile", "content": caddy_conf})

    elif proxy == "traefik":
        import yaml as _yaml
        traefik_cfg = {
            "http": {
                "routers": {
                    "app": {
                        "rule": f"Host(`{domain}`)",
                        "service": "app",
                        "entryPoints": ["websecure"],
                        "tls": {"certResolver": "letsencrypt"},
                    },
                },
                "services": {
                    "app": {
                        "loadBalancer": {
                            "servers": [{"url": upstream}],
                        },
                    },
                },
            },
        }
        files.append({
            "path": "cdn/traefik.yml",
            "content": _yaml.dump(traefik_cfg, default_flow_style=False, sort_keys=False),
        })

    elif proxy == "cloudflared":
        import yaml as _yaml
        all_hosts = [domain] + [
            f"{s}.{domain}" if "." not in s else s for s in subdomains
        ]
        # cloudflared config.yml with ingress rules
        ingress_rules: list[dict] = []
        for host in all_hosts:
            ingress_rules.append({
                "hostname": host,
                "service": upstream,
            })
        # Catch-all (required by cloudflared)
        ingress_rules.append({"service": "http_status:404"})
        cloudflared_cfg = {
            "tunnel": "<YOUR-TUNNEL-ID>",
            "credentials-file": "/etc/cloudflared/<YOUR-TUNNEL-ID>.json",
            "ingress": ingress_rules,
        }
        files.append({
            "path": "cdn/cloudflared.yml",
            "content": (
                "# Cloudflare Tunnel — generated by DevOps Control Plane\n"
                "# Replace <YOUR-TUNNEL-ID> with your actual tunnel ID\n"
                "# Run: cloudflared tunnel login && cloudflared tunnel create <name>\n\n"
                + _yaml.dump(cloudflared_cfg, default_flow_style=False, sort_keys=False)
            ),
        })

    # ── 5. K8s Ingress (if routes provided) ────────────────────────
    k8s_routes = data.get("k8s_routes") or []
    if k8s_routes:
        import yaml as _yaml

        ingress_rules = []
        tls_hosts = []
        for route in k8s_routes:
            host = route.get("host", domain)
            svc = route.get("service", "web")
            port = route.get("port", 80)
            ingress_rules.append({
                "host": host,
                "http": {
                    "paths": [{
                        "path": "/",
                        "pathType": "Prefix",
                        "backend": {
                            "service": {
                                "name": svc,
                                "port": {"number": int(port)},
                            },
                        },
                    }],
                },
            })
            tls_hosts.append(host)

        tls_block: list[dict] = []
        if ssl_strategy in ("letsencrypt", "certmanager", "managed"):
            tls_block = [{
                "hosts": tls_hosts,
                "secretName": f"{domain.replace('.', '-')}-tls",
            }]

        ingress_manifest = {
            "apiVersion": "networking.k8s.io/v1",
            "kind": "Ingress",
            "metadata": {
                "name": f"{domain.replace('.', '-')}-ingress",
                "annotations": {},
            },
            "spec": {
                "rules": ingress_rules,
            },
        }

        # Annotations
        ingress_ctrl = data.get("ingress", "nginx")
        if ingress_ctrl == "nginx":
            ingress_manifest["metadata"]["annotations"][
                "kubernetes.io/ingress.class"
            ] = "nginx"
        elif ingress_ctrl == "traefik":
            ingress_manifest["metadata"]["annotations"][
                "kubernetes.io/ingress.class"
            ] = "traefik"
        elif ingress_ctrl == "alb":
            ingress_manifest["metadata"]["annotations"][
                "kubernetes.io/ingress.class"
            ] = "alb"

        if data.get("certmanager"):
            ingress_manifest["metadata"]["annotations"][
                "cert-manager.io/cluster-issuer"
            ] = "letsencrypt-prod"

        if tls_block:
            ingress_manifest["spec"]["tls"] = tls_block

        ingress_yaml = _yaml.dump(
            ingress_manifest,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )
        files.append({"path": "k8s/ingress.yaml", "content": ingress_yaml})

        # cert-manager manifests
        if data.get("certmanager"):
            issuer = {
                "apiVersion": "cert-manager.io/v1",
                "kind": "ClusterIssuer",
                "metadata": {"name": "letsencrypt-prod"},
                "spec": {
                    "acme": {
                        "server": "https://acme-v02.api.letsencrypt.org/directory",
                        "email": f"admin@{domain}",
                        "privateKeySecretRef": {"name": "letsencrypt-prod"},
                        "solvers": [{"http01": {"ingress": {"class": ingress_ctrl}}}],
                    },
                },
            }
            files.append({
                "path": "k8s/cert-manager/cluster-issuer.yaml",
                "content": _yaml.dump(issuer, default_flow_style=False, sort_keys=False),
            })

            cert = {
                "apiVersion": "cert-manager.io/v1",
                "kind": "Certificate",
                "metadata": {"name": f"{domain.replace('.', '-')}-cert"},
                "spec": {
                    "secretName": f"{domain.replace('.', '-')}-tls",
                    "issuerRef": {
                        "name": "letsencrypt-prod",
                        "kind": "ClusterIssuer",
                    },
                    "dnsNames": tls_hosts,
                },
            }
            files.append({
                "path": "k8s/cert-manager/certificate.yaml",
                "content": _yaml.dump(cert, default_flow_style=False, sort_keys=False),
            })

    # ── 6. Write files to disk ─────────────────────────────────────
    files_created: list[str] = []
    skipped: list[str] = []

    for f in files:
        fpath = root / f["path"]
        if fpath.exists() and not overwrite:
            skipped.append(f["path"])
            continue
        fpath.parent.mkdir(parents=True, exist_ok=True)
        fpath.write_text(f["content"], encoding="utf-8")
        files_created.append(f["path"])

    # ── 7. Activity event ──────────────────────────────────────────
    devops_cache.record_event(
        root,
        label="🌐 DNS & CDN Setup",
        summary=(
            f"DNS/CDN configured for {domain} "
            f"({len(files_created)} file{'s' if len(files_created) != 1 else ''}"
            + (f", {len(skipped)} skipped" if skipped else "")
            + ")"
        ),
        detail={
            "files_created": files_created,
            "files_skipped": skipped,
            "domain": domain,
            "dns_provider": dns_provider,
            "cdn_provider": cdn_provider,
        },
        card="wizard",
        action="configured",
        target="dns",
    )

    resp: dict = {
        "ok": True,
        "message": f"DNS & CDN configuration generated ({len(files_created)} files)",
        "files_created": files_created,
    }
    if skipped:
        resp["files_skipped"] = skipped
        resp["message"] += f", {len(skipped)} skipped (already exist)"

    return resp
