# Ruby stack — detection and capabilities
name: ruby
icon: "💎"
description: "Ruby project"
detail: >
  Ruby is a dynamic, object-oriented language known for developer happiness
  and elegant syntax. Its ecosystem is built around Bundler and gems.
  
  Technical: Ruby project detected via Gemfile (Bundler). Provides install,
  lint (rubocop), test (rspec), and console (irb) capabilities.
domain: service

detection:
  files_any_of:
    - Gemfile
    - Rakefile
  files_all_of: []
  content_contains: {}

requires:
  - adapter: shell
    min_version: ""

capabilities:
  - name: install
    adapter: shell
    command: "bundle install"
    description: "Install dependencies"
  - name: lint
    adapter: shell
    command: "bundle exec rubocop"
    description: "Run RuboCop linter"
  - name: format
    adapter: shell
    command: "bundle exec rubocop -A"
    description: "Auto-correct with RuboCop"
  - name: test
    adapter: shell
    command: "bundle exec rspec"
    description: "Run tests"
  - name: console
    adapter: shell
    command: "bundle exec irb"
    description: "Open interactive console"
