"""
Pages CI — generates GitHub Actions deploy workflow.

Creates a deploy-pages.yml workflow that builds all segments,
merges outputs, and pushes to GitHub Pages.
"""

from __future__ import annotations

from pathlib import Path

from src.core.services.pages_builders import get_builder
from src.core.services.pages_engine import get_segments


def generate_ci_workflow(project_root: Path) -> dict:
    """Generate a GitHub Actions workflow for Pages deployment.

    Creates .github/workflows/deploy-pages.yml that:
    1. Checks out the repo
    2. Installs builder dependencies
    3. Builds all segments
    4. Merges outputs
    5. Deploys to GitHub Pages

    Returns:
        Dict with {ok, path, error}.
    """
    segments = get_segments(project_root)
    if not segments:
        return {"ok": False, "error": "No segments configured"}

    # Detect required builders
    builders_used = set(seg.builder for seg in segments)

    # Build install steps
    install_steps: list[str] = []
    build_commands: list[str] = []

    for seg in segments:
        builder = seg.builder
        src = seg.source
        path = seg.path.strip("/") or seg.name

        if builder == "raw":
            build_commands.append(f"mkdir -p _merged/{path}")
            build_commands.append(f"cp -r {src}/. _merged/{path}/")

        elif builder == "mkdocs":
            if "mkdocs" not in [s for s in install_steps if "mkdocs" in s]:
                install_steps.append("pip install mkdocs mkdocs-material")
            build_commands.append(
                f"mkdocs build --config-file .pages/{seg.name}/mkdocs.yml"
            )
            build_commands.append(f"cp -r .pages/{seg.name}/build/. _merged/{path}/")

        elif builder == "hugo":
            build_commands.append(
                f"hugo --source .pages/{seg.name} --destination build"
            )
            build_commands.append(f"cp -r .pages/{seg.name}/build/. _merged/{path}/")

        elif builder == "docusaurus":
            if "node" not in [s for s in install_steps if "node" in s]:
                install_steps.append("# Node.js setup handled by actions/setup-node")
            # CI builds from the committed source, not local .pages workspace.
            # The scaffold files (package.json, docusaurus.config.ts, etc.)
            # must already exist in .pages/<name>/ (committed to repo).
            ws = f".pages/{seg.name}"
            build_commands.append(f"cp -r {src}/. {ws}/docs/")
            build_commands.append(f"cd {ws} && npm ci && npx docusaurus build --out-dir build")
            build_commands.append(f"cp -r {ws}/build/. _merged/{path}/")

    # Assemble workflow
    install_block = "\n          ".join(install_steps) if install_steps else "echo 'No additional deps'"
    build_block = "\n          ".join(build_commands)

    needs_node = "docusaurus" in builders_used
    needs_python = "mkdocs" in builders_used or "sphinx" in builders_used
    needs_hugo = "hugo" in builders_used

    setup_steps = ""
    if needs_python:
        setup_steps += """
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
"""
    if needs_node:
        setup_steps += """
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
"""
    if needs_hugo:
        setup_steps += """
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
"""

    workflow = f"""# Auto-generated by DevOps Control Plane
# Deploy documentation to GitHub Pages
name: Deploy Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
{setup_steps}
      - name: Install dependencies
        run: |
          {install_block}

      - name: Build segments
        run: |
          mkdir -p _merged
          {build_block}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _merged

  deploy:
    environment:
      name: github-pages
      url: ${{{{ steps.deployment.outputs.page_url }}}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
"""

    # Write workflow file
    workflow_dir = project_root / ".github" / "workflows"
    workflow_dir.mkdir(parents=True, exist_ok=True)
    workflow_path = workflow_dir / "deploy-pages.yml"
    workflow_path.write_text(workflow, encoding="utf-8")

    return {
        "ok": True,
        "path": str(workflow_path.relative_to(project_root)),
        "builders": list(builders_used),
    }
