"""
Terraform scaffolding — HCL template generation.

Generates main.tf, variables.tf, outputs.tf, and .gitignore
for a new Terraform project.
"""

from __future__ import annotations

from pathlib import Path

from src.core.services.audit_helpers import make_auditor

_audit = make_auditor("terraform")


# ── Templates ───────────────────────────────────────────────────────


_MAIN_TF_TEMPLATE = '''# ── Main Terraform Configuration ─────────────────────────────────
# Generated by DevOps Control Plane

terraform {{
  required_version = ">= 1.5.0"

  required_providers {{
    {provider_block}
  }}

  {backend_block}
}}

provider "{provider}" {{
  {provider_config}
}}

# ── Resources ────────────────────────────────────────────────────

# Add your resources here
'''

_VARIABLES_TF_TEMPLATE = '''# ── Variables ────────────────────────────────────────────────────
# Generated by DevOps Control Plane

variable "project" {{
  description = "Project name"
  type        = string
  default     = "{project_name}"
}}

variable "environment" {{
  description = "Environment (dev, staging, production)"
  type        = string
  default     = "dev"

  validation {{
    condition     = contains(["dev", "staging", "production"], var.environment)
    error_message = "Environment must be dev, staging, or production."
  }}
}}

variable "region" {{
  description = "Cloud region"
  type        = string
  default     = "{default_region}"
}}

variable "tags" {{
  description = "Common resource tags"
  type        = map(string)
  default = {{
    Project     = "{project_name}"
    ManagedBy   = "terraform"
  }}
}}
'''

_OUTPUTS_TF_TEMPLATE = '''# ── Outputs ──────────────────────────────────────────────────────
# Generated by DevOps Control Plane

# output "example_id" {{
#   description = "ID of the example resource"
#   value       = resource_type.resource_name.id
# }}
'''


# ── Data access ─────────────────────────────────────────────────────


def _provider_blocks() -> dict[str, dict]:
    """Terraform cloud provider configs — loaded from DataRegistry."""
    from src.core.data import get_registry
    return get_registry().terraform_providers


def _backend_blocks() -> dict[str, str]:
    """Terraform backend HCL templates — loaded from DataRegistry."""
    from src.core.data import get_registry
    return get_registry().terraform_backends


# ── Generator ───────────────────────────────────────────────────────


def generate_terraform(
    project_root: Path,
    provider: str = "aws",
    *,
    backend: str = "local",
    project_name: str = "",
) -> dict:
    """Generate Terraform scaffolding.

    Returns:
        {"ok": True, "files": [{path, content, reason}, ...]}
    """
    from src.core.models.template import GeneratedFile

    if not project_name:
        project_name = project_root.name

    providers = _provider_blocks()
    prov_config = providers.get(provider)
    if not prov_config:
        return {"error": f"Unknown provider: {provider}. Available: {', '.join(providers.keys())}"}

    # Build provider block
    provider_block = f"""{provider} = {{
      source  = "{prov_config['source']}"
      version = "{prov_config['version']}"
    }}"""

    # Build backend block
    backends = _backend_blocks()
    backend_template = backends.get(backend, backends["local"])
    backend_block = backend_template.format(
        project=project_name.replace("-", "").replace("_", ""),
        region=prov_config.get("default_region", "us-east-1"),
    )

    # main.tf
    main_content = _MAIN_TF_TEMPLATE.format(
        provider_block=provider_block,
        backend_block=backend_block,
        provider=provider,
        provider_config=prov_config["config"],
    )

    # variables.tf
    vars_content = _VARIABLES_TF_TEMPLATE.format(
        project_name=project_name,
        default_region=prov_config.get("default_region", "us-east-1"),
    )

    files: list[dict] = []

    files.append(GeneratedFile(
        path="terraform/main.tf",
        content=main_content,
        overwrite=False,
        reason=f"Terraform main config ({provider} provider, {backend} backend)",
    ).model_dump())

    files.append(GeneratedFile(
        path="terraform/variables.tf",
        content=vars_content,
        overwrite=False,
        reason="Terraform variables with validation",
    ).model_dump())

    files.append(GeneratedFile(
        path="terraform/outputs.tf",
        content=_OUTPUTS_TF_TEMPLATE,
        overwrite=False,
        reason="Terraform outputs (template)",
    ).model_dump())

    # .gitignore for terraform
    tf_gitignore = """# Terraform
.terraform/
*.tfstate
*.tfstate.*
*.tfplan
crash.log
*.tfvars
!terraform.tfvars.example
.terraform.lock.hcl
"""
    files.append(GeneratedFile(
        path="terraform/.gitignore",
        content=tf_gitignore,
        overwrite=False,
        reason="Terraform .gitignore",
    ).model_dump())

    _audit(
        "📝 Terraform Generated",
        f"Scaffolding generated (provider={provider}, backend={backend})",
        action="generated", target="terraform",
        after_state={"provider": provider, "backend": backend},
    )
    return {"ok": True, "files": files}
