"""Compatibility tests for web.

Auto-generated by DevOps Control Plane.
Verifies imports, public API, version compatibility, and dependency availability.
Regenerate with: module upgrade → "Generate compatibility tests"
"""
from __future__ import annotations

import importlib
import sys

import pytest


# ── 1. Import Verification ──────────────────────────────────────
# Every .py file in the module should be importable without errors.

_MODULE_PATHS = [
    "src.ui.web",
    "src.ui.web.cdp_client",
    "src.ui.web.helpers",
    "src.ui.web.request_timing",
    "src.ui.web.routes",
    "src.ui.web.routes.api",
    "src.ui.web.routes.api.audit",
    "src.ui.web.routes.api.batch",
    "src.ui.web.routes.api.stacks",
    "src.ui.web.routes.api.status",
    "src.ui.web.routes.artifacts",
    "src.ui.web.routes.artifacts.api",
    "src.ui.web.routes.audit",
    "src.ui.web.routes.audit.analysis",
    "src.ui.web.routes.audit.async_scan",
    "src.ui.web.routes.audit.deep_detection",
    "src.ui.web.routes.audit.offline_cache",
    "src.ui.web.routes.audit.staging",
    "src.ui.web.routes.audit.tool_execution",
    "src.ui.web.routes.audit.tool_install",
    "src.ui.web.routes.backup",
    "src.ui.web.routes.backup.archive",
    "src.ui.web.routes.backup.ops",
    "src.ui.web.routes.backup.restore",
    "src.ui.web.routes.backup.tree",
    "src.ui.web.routes.cdp_test",
    "src.ui.web.routes.cdp_test.browser",
    "src.ui.web.routes.cdp_test.io",
    "src.ui.web.routes.cdp_test.recording",
    "src.ui.web.routes.cdp_test.replay",
    "src.ui.web.routes.cdp_test.suites",
    "src.ui.web.routes.changelog",
    "src.ui.web.routes.chat",
    "src.ui.web.routes.chat.messages",
    "src.ui.web.routes.chat.refs",
    "src.ui.web.routes.chat.sync",
    "src.ui.web.routes.chat.threads",
    "src.ui.web.routes.ci",
    "src.ui.web.routes.ci.generate",
    "src.ui.web.routes.ci.status",
    "src.ui.web.routes.config",
    "src.ui.web.routes.content",
    "src.ui.web.routes.content.files",
    "src.ui.web.routes.content.helpers",
    "src.ui.web.routes.content.manage",
    "src.ui.web.routes.content.outline",
    "src.ui.web.routes.content.peek",
    "src.ui.web.routes.content.preview",
    "src.ui.web.routes.dependencies",
    "src.ui.web.routes.dependencies.api",
]


@pytest.mark.parametrize("module_path", _MODULE_PATHS)
def test_module_importable(module_path):
    """Verify each module file can be imported."""
    importlib.import_module(module_path)


# ── 3. Version Compatibility ────────────────────────────────────
# The module claims Python >=3.8 support.

def test_python_version_floor():
    """Verify we are running on at least the declared minimum."""
    assert sys.version_info >= (3, 8), (
        f"Module requires Python >=3.8, running on {sys.version_info}"
    )


# ── 4. Dependency Imports ────────────────────────────────────────
# All declared dependencies should be importable.

_DECLARED_DEPS = [
    "flask",
    "pytest",
]


@pytest.mark.parametrize("dep", _DECLARED_DEPS)
def test_dependency_importable(dep):
    """Verify each declared dependency can be imported."""
    try:
        importlib.import_module(dep)
    except ImportError:
        pytest.skip(f"{dep} not installed in this environment")
