"""
docker-compose.yml generator — produce a compose file from detected modules.

Creates a basic compose structure with services for each module
that has a Dockerfile or a known stack.
"""

from __future__ import annotations

from pathlib import Path

from src.core.models.template import GeneratedFile


# Default port per stack family
_DEFAULT_PORTS: dict[str, int] = {
    "python": 8000,
    "node": 3000,
    "typescript": 3000,
    "go": 8080,
    "rust": 8080,
    "java": 8080,
    "dotnet": 8080,
    "elixir": 4000,
    "ruby": 3000,
    "static-site": 80,
}


def _resolve_port(stack_name: str) -> int:
    """Resolve default port for a stack."""
    if stack_name in _DEFAULT_PORTS:
        return _DEFAULT_PORTS[stack_name]
    for prefix, port in _DEFAULT_PORTS.items():
        if stack_name.startswith(prefix + "-"):
            return port
    return 8080


def generate_compose(
    project_root: Path,
    modules: list[dict],
    *,
    project_name: str = "",
) -> GeneratedFile | None:
    """Generate a docker-compose.yml from detected modules.

    Args:
        project_root: Project root directory.
        modules: List of module dicts with at minimum:
                 ``name``, ``path``, ``stack_name`` (or ``effective_stack``).
        project_name: Optional project name for compose.

    Returns:
        GeneratedFile or None if no modules qualify.
    """
    services: list[str] = []

    for mod in modules:
        name = mod.get("name", "")
        path = mod.get("path", "")
        stack = mod.get("effective_stack", mod.get("stack_name", ""))

        if not name or not path:
            continue

        # Skip docs/markdown modules
        if stack in ("markdown",) or mod.get("domain") == "docs":
            continue

        port = _resolve_port(stack)

        # Check if module has its own Dockerfile
        module_dir = project_root / path
        has_own_dockerfile = (module_dir / "Dockerfile").is_file()
        build_context = f"./{path}" if has_own_dockerfile else "."

        service_block = f"""\
  {name}:
    build:
      context: {build_context}
      dockerfile: Dockerfile
    ports:
      - "{port}:{port}"
    restart: unless-stopped
    environment:
      - NODE_ENV=production"""

        services.append(service_block)

    if not services:
        return None

    header = f"# Generated by DevOps Control Plane\n"
    if project_name:
        header += f"name: {project_name}\n"

    content = header + "\nservices:\n" + "\n\n".join(services) + "\n"

    return GeneratedFile(
        path="docker-compose.yml",
        content=content,
        overwrite=False,
        reason=f"Generated docker-compose.yml for {len(services)} service(s)",
    )
