"""
GitHub Actions workflow generator.

BACKWARD COMPATIBILITY SHIM — implementation has moved to:
    - ``wf_ci_jobs.py``      — per-language CI job generators
    - ``wf_docker.py``       — Docker build/push CI job
    - ``wf_k8s_deploy.py``   — kubectl/skaffold/helm deploy jobs
    - ``wf_terraform.py``    — Terraform CI job
    - ``wf_post_deploy.py``  — DNS verify + CDN purge post-deploy
    - ``wf_lint.py``         — lightweight lint workflow

This file re-exports everything so existing imports continue to work.
The ``generate_ci`` public API function remains here as it ties together
the CI job registry from ``wf_ci_jobs.py``.
"""

from __future__ import annotations

from pathlib import Path

from src.core.models.template import GeneratedFile

# ── CI jobs (wf_ci_jobs.py) ─────────────────────────────────────
from src.core.services.generators.wf_ci_jobs import (  # noqa: F401
    _CI_JOBS,
    _go_ci_job,
    _java_gradle_ci_job,
    _java_maven_ci_job,
    _node_ci_job,
    _python_ci_job,
    _resolve_job,
    _rust_ci_job,
)

# ── Docker (wf_docker.py) ──────────────────────────────────────
from src.core.services.generators.wf_docker import (  # noqa: F401
    _docker_ci_job,
    generate_docker_ci,
)

# ── K8s deploy (wf_k8s_deploy.py) ──────────────────────────────
from src.core.services.generators.wf_k8s_deploy import (  # noqa: F401
    _helm_deploy_ci_job,
    _kubeconfig_step,
    _kubectl_deploy_ci_job,
    _skaffold_deploy_ci_job,
    generate_k8s_deploy_ci,
)

# ── Terraform (wf_terraform.py) ────────────────────────────────
from src.core.services.generators.wf_terraform import (  # noqa: F401
    _TERRAFORM_CREDENTIALS,
    _terraform_ci_job,
    generate_terraform_ci,
)

# ── Post-deploy (wf_post_deploy.py) ────────────────────────────
from src.core.services.generators.wf_post_deploy import (  # noqa: F401
    _CDN_PURGE_COMMANDS,
    _cdn_purge_ci_step,
    _dns_verify_ci_step,
    generate_deploy_post_steps,
)

# ── Lint (wf_lint.py) ──────────────────────────────────────────
from src.core.services.generators.wf_lint import (  # noqa: F401
    generate_lint,
)


# ── Public API: generate_ci ────────────────────────────────────


def generate_ci(
    project_root: Path,
    stack_names: list[str],
    *,
    project_name: str = "",
) -> GeneratedFile | None:
    """Generate a comprehensive CI workflow for detected stacks.

    Args:
        project_root: Project root directory.
        stack_names: List of detected stack names.
        project_name: Optional project name for workflow naming.

    Returns:
        GeneratedFile or None if no stacks match.
    """
    job_blocks: list[str] = []
    seen_generators: set[int] = set()

    for name in stack_names:
        gen = _resolve_job(name)
        if gen and id(gen) not in seen_generators:
            job_blocks.append(gen())
            seen_generators.add(id(gen))

    if not job_blocks:
        return None

    wf_name = f"{project_name} CI" if project_name else "CI"

    header = f"""\
# Generated by DevOps Control Plane
name: {wf_name}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
"""

    content = header + "\n".join(job_blocks)

    return GeneratedFile(
        path=".github/workflows/ci.yml",
        content=content,
        overwrite=False,
        reason=f"Generated CI workflow for stacks: {', '.join(stack_names)}",
    )
