"""
Docker build + push CI job generator.

Produces a GitHub Actions job that builds Docker images with Buildx,
logs in to various registries (GHCR, DockerHub, custom), and pushes
on push events.
"""

from __future__ import annotations

from src.core.models.template import GeneratedFile


def _docker_ci_job(
    *,
    image_name: str = "app",
    registry: str = "",
    registry_type: str = "",
    build_args: dict[str, str] | None = None,
    use_buildx: bool = True,
    use_cache: bool = True,
    dockerfile: str = "Dockerfile",
    context: str = ".",
) -> str:
    """Docker build + push CI job.

    Args:
        image_name: Image name (without registry prefix).
        registry: Registry URL (e.g. 'ghcr.io/org').
        registry_type: 'ghcr' | 'dockerhub' | 'custom' | ''.
        build_args: Docker build args to pass with --build-arg.
        use_buildx: Whether to use docker/setup-buildx-action.
        use_cache: Whether to use GHA layer caching.
        dockerfile: Path to Dockerfile.
        context: Build context directory.
    """
    steps: list[str] = []

    # Checkout
    steps.append("      - uses: actions/checkout@v4")

    # Buildx
    if use_buildx:
        steps.append("""\
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3""")

    # Registry login
    if registry_type == "ghcr":
        steps.append("""\
      - name: Log in to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}""")
    elif registry_type == "dockerhub":
        steps.append("""\
      - name: Log in to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}""")
    elif registry_type == "custom" and registry:
        steps.append(f"""\
      - name: Log in to registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: {registry}
          username: ${{{{ secrets.REGISTRY_USERNAME }}}}
          password: ${{{{ secrets.REGISTRY_PASSWORD }}}}""")

    # Build image tag
    if registry:
        full_image = f"{registry}/{image_name}"
    else:
        full_image = image_name

    # Build command
    build_parts: list[str] = []
    build_parts.append(f"          docker build")
    build_parts.append(f"            -f {dockerfile}")
    build_parts.append(f"            -t {full_image}:${{{{{{ github.sha }}}}}}")
    build_parts.append(f"            -t {full_image}:latest")

    if build_args:
        for key, val in build_args.items():
            build_parts.append(f"            --build-arg {key}={val}")

    if use_cache:
        build_parts.append("            --cache-from type=gha")
        build_parts.append("            --cache-to type=gha,mode=max")

    build_parts.append(f"            {context}")

    build_step = "\n".join(build_parts)
    steps.append(f"""\
      - name: Build Docker image
        run: |
{build_step}""")

    # Push (only on push to main, only if registry configured)
    if registry:
        steps.append(f"""\
      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker push {full_image}:${{{{{{ github.sha }}}}}}
          docker push {full_image}:latest""")

    steps_str = "\n\n".join(steps)

    return f"""\
  docker:
    name: Docker — build{" & push" if registry else ""}
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push'

    steps:
{steps_str}
"""


def generate_docker_ci(
    docker_services: list[dict],
    *,
    project_name: str = "",
    test_job: str = "",
) -> GeneratedFile | None:
    """Generate a Docker build/push CI workflow.

    Args:
        docker_services: List of dicts, each with:
            name, image, registry, registry_type, build_args,
            use_buildx, use_cache, dockerfile, context.
        project_name: For the workflow name.
        test_job: If provided, include this test job YAML before docker jobs.

    Returns:
        GeneratedFile or None if no services.
    """
    if not docker_services:
        return None

    wf_name = f"{project_name} Docker CI" if project_name else "Docker CI"

    header = f"""\
# Generated by DevOps Control Plane
name: {wf_name}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
"""
    # Minimal test job placeholder so docker can depend on it
    test_block = test_job or """\
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: echo "Tests placeholder"
"""

    docker_blocks: list[str] = []
    for svc in docker_services:
        job_yaml = _docker_ci_job(
            image_name=svc.get("name", "app"),
            registry=svc.get("registry", ""),
            registry_type=svc.get("registry_type", ""),
            build_args=svc.get("build_args"),
            use_buildx=svc.get("use_buildx", True),
            use_cache=svc.get("use_cache", True),
            dockerfile=svc.get("dockerfile", "Dockerfile"),
            context=svc.get("context", "."),
        )
        # For multiple services, make job names unique
        if len(docker_services) > 1:
            svc_name = svc.get("name", "app")
            job_yaml = job_yaml.replace(
                "  docker:", f"  docker-{svc_name}:", 1
            )
        docker_blocks.append(job_yaml)

    content = header + test_block + "\n" + "\n".join(docker_blocks)

    return GeneratedFile(
        path=".github/workflows/docker.yml",
        content=content,
        overwrite=False,
        reason=f"Docker CI for {len(docker_services)} service(s)",
    )
