"""
Lint-only workflow generator.

Produces a lightweight GitHub Actions lint workflow separate from the
full CI pipeline. Currently supports Python (ruff + mypy) and
Node.js (eslint + prettier) lint steps.
"""

from __future__ import annotations

from pathlib import Path

from src.core.models.template import GeneratedFile


def _python_lint_steps() -> str:
    return """\
      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (ruff)
        run: ruff format --check .

      - name: Type check (mypy)
        run: mypy src/ --ignore-missing-imports
"""


def _node_lint_steps() -> str:
    return """\
      - name: Lint (eslint)
        run: npm run lint --if-present

      - name: Format check (prettier)
        run: npx prettier --check . 2>/dev/null || true
"""


_LINT_STEPS: dict[str, callable] = {
    "python": _python_lint_steps,
    "node": _node_lint_steps,
    "typescript": _node_lint_steps,
}


def generate_lint(
    project_root: Path,
    stack_names: list[str],
) -> GeneratedFile | None:
    """Generate a lightweight lint-only workflow.

    Returns:
        GeneratedFile or None.
    """
    setup_blocks: list[str] = []
    lint_blocks: list[str] = []

    for name in stack_names:
        # Resolve lint steps
        gen = _LINT_STEPS.get(name)
        if not gen:
            for prefix, g in _LINT_STEPS.items():
                if name.startswith(prefix):
                    gen = g
                    break

        if gen and gen not in [g for g in lint_blocks]:
            if name.startswith("python") or name == "python":
                setup_blocks.append("""\
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install lint tools
        run: pip install ruff mypy
""")
            elif name.startswith("node") or name == "node" or name == "typescript":
                setup_blocks.append("""\
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci
""")
            lint_blocks.append(gen())

    if not lint_blocks:
        return None

    content = """\
# Generated by DevOps Control Plane
name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

""" + "\n".join(setup_blocks) + "\n" + "\n".join(lint_blocks)

    return GeneratedFile(
        path=".github/workflows/lint.yml",
        content=content,
        overwrite=False,
        reason=f"Generated lint workflow for stacks: {', '.join(stack_names)}",
    )
