"""
Post-deploy CI step generators — DNS verification and CDN cache purge.

Produces a GitHub Actions workflow triggered after the Deploy workflow completes.
Supports DNS resolution checks (via dig) and cache purge for Cloudflare,
CloudFront, and Netlify.
"""

from __future__ import annotations

from src.core.models.template import GeneratedFile


# CDN provider → purge command + required secrets
_CDN_PURGE_COMMANDS: dict[str, dict] = {
    "cloudflare": {
        "run": (
            'curl -X POST "https://api.cloudflare.com/client/v4'
            '/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" '
            '-H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" '
            '-H "Content-Type: application/json" '
            "--data '{\"purge_everything\":true}'"
        ),
        "secrets": {
            "CLOUDFLARE_API_TOKEN": "${{ secrets.CLOUDFLARE_API_TOKEN }}",
            "CLOUDFLARE_ZONE_ID": "${{ secrets.CLOUDFLARE_ZONE_ID }}",
        },
    },
    "cloudfront": {
        "run": (
            "aws cloudfront create-invalidation "
            "--distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} "
            '--paths "/*"'
        ),
        "secrets": {
            "AWS_ACCESS_KEY_ID": "${{ secrets.AWS_ACCESS_KEY_ID }}",
            "AWS_SECRET_ACCESS_KEY": "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
            "CLOUDFRONT_DISTRIBUTION_ID": "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}",
        },
    },
    "netlify": {
        "run": "npx netlify-cli deploy --prod --dir=.",
        "secrets": {
            "NETLIFY_AUTH_TOKEN": "${{ secrets.NETLIFY_AUTH_TOKEN }}",
            "NETLIFY_SITE_ID": "${{ secrets.NETLIFY_SITE_ID }}",
        },
    },
}


def _dns_verify_ci_step(domains: list[str]) -> str:
    """Build a DNS verification step that checks each domain with dig."""
    checks = []
    for domain in domains:
        checks.append(
            f'echo "Checking {domain}..."\n'
            f'          dig +short {domain} A || echo "WARNING: {domain} has no A record"'
        )
    check_block = "\n          ".join(checks)

    return f"""\
      - name: Verify DNS resolution
        run: |
          {check_block}
"""


def _cdn_purge_ci_step(cdn_provider: str) -> str:
    """Build a CDN cache purge step for the given provider."""
    spec = _CDN_PURGE_COMMANDS.get(cdn_provider)
    if not spec:
        return ""
    return f"""\
      - name: Purge CDN cache ({cdn_provider})
        run: |
          {spec['run']}
"""


def generate_deploy_post_steps(
    deploy_config: dict,
    *,
    project_name: str = "",
) -> GeneratedFile | None:
    """Generate a post-deploy workflow with DNS verification and CDN purge.

    Args:
        deploy_config: Dict with:
            domains: List of domains to verify DNS for.
            cdn_provider: 'cloudflare' | 'cloudfront' | 'netlify'
            project_name: Optional project name for workflow naming.
        project_name: For workflow naming (can also be in config).

    Returns:
        GeneratedFile or None if nothing to do.
    """
    domains = deploy_config.get("domains", [])
    cdn_provider = deploy_config.get("cdn_provider", "")
    proj = project_name or deploy_config.get("project_name", "")

    if not domains and not cdn_provider:
        return None

    # Build steps
    steps: list[str] = ["      - uses: actions/checkout@v4\n"]

    if domains:
        steps.append(_dns_verify_ci_step(domains))

    if cdn_provider:
        purge_step = _cdn_purge_ci_step(cdn_provider)
        if purge_step:
            steps.append(purge_step)

    # Build env block from CDN secrets
    env_lines: list[str] = []
    if cdn_provider and cdn_provider in _CDN_PURGE_COMMANDS:
        secrets = _CDN_PURGE_COMMANDS[cdn_provider]["secrets"]
        for key, val in secrets.items():
            env_lines.append(f"      {key}: {val}")

    env_block = ""
    if env_lines:
        env_block = "\n    env:\n" + "\n".join(env_lines) + "\n"

    wf_name = f"{proj} Post-Deploy" if proj else "Post-Deploy"

    steps_block = "\n".join(steps)

    content = f"""\
# Generated by DevOps Control Plane
name: {wf_name}

on:
  workflow_run:
    workflows: ["Deploy"]
    types: [completed]

permissions:
  contents: read

jobs:
  post_deploy:
    name: Post-Deploy Checks
    runs-on: ubuntu-latest
    if: ${{{{ github.event.workflow_run.conclusion == 'success' }}}}
{env_block}
    steps:
{steps_block}
"""

    return GeneratedFile(
        path=".github/workflows/post-deploy.yml",
        content=content,
        overwrite=False,
        reason=f"Post-deploy checks (DNS verify: {len(domains)} domain(s), CDN: {cdn_provider or 'none'})",
    )
