"""
Terraform CI job generator.

Produces a GitHub Actions workflow for Terraform: init → validate → plan → apply.
Supports AWS, GCP, and Azure credential injection via GHA secrets.
PR events get plan only; push to main gets plan + apply.
"""

from __future__ import annotations

from src.core.models.template import GeneratedFile


# Provider → environment variables needed for authentication
_TERRAFORM_CREDENTIALS: dict[str, dict[str, str]] = {
    "aws": {
        "AWS_ACCESS_KEY_ID": "${{ secrets.AWS_ACCESS_KEY_ID }}",
        "AWS_SECRET_ACCESS_KEY": "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
    },
    "google": {
        "GOOGLE_CREDENTIALS": "${{ secrets.GOOGLE_CREDENTIALS }}",
    },
    "azurerm": {
        "ARM_CLIENT_ID": "${{ secrets.ARM_CLIENT_ID }}",
        "ARM_CLIENT_SECRET": "${{ secrets.ARM_CLIENT_SECRET }}",
        "ARM_TENANT_ID": "${{ secrets.ARM_TENANT_ID }}",
        "ARM_SUBSCRIPTION_ID": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
    },
}


def _terraform_ci_job(
    *,
    provider: str = "aws",
    working_directory: str = "terraform",
    workspaces: list[str] | None = None,
) -> str:
    """Terraform CI job: init → validate → plan → apply (guarded).

    PR  → plan only (no apply)
    Push to main → plan + apply -auto-approve
    """
    # Build env block for credentials
    creds = _TERRAFORM_CREDENTIALS.get(provider, {})
    env_lines = []
    for key, val in creds.items():
        env_lines.append(f"      {key}: {val}")
    env_block = "\n".join(env_lines)

    # Workspace step (optional)
    workspace_step = ""
    if workspaces:
        # Use TF_WORKSPACE environment variable with first workspace as default
        workspace_step = f"""
      - name: Select Terraform workspace
        run: terraform workspace select {workspaces[0]} || terraform workspace new {workspaces[0]}
"""

    return f"""\
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: {working_directory}

    env:
{env_block}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
{workspace_step}
      - name: Terraform init
        run: terraform init -no-color

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        run: terraform plan -no-color -input=false

      - name: Terraform apply
        if: github.event_name == 'push'
        run: terraform apply -no-color -input=false -auto-approve
"""


def generate_terraform_ci(
    terraform_config: dict,
    *,
    project_name: str = "",
) -> GeneratedFile | None:
    """Generate a Terraform CI workflow (GitHub Actions).

    Args:
        terraform_config: Dict with:
            provider: 'aws' | 'google' | 'azurerm'
            working_directory: Path to terraform dir (default 'terraform')
            workspaces: Optional list of workspace names
            project_name: Optional project name for workflow naming
        project_name: For workflow naming (can also be in config).

    Returns:
        GeneratedFile or None.
    """
    provider = terraform_config.get("provider", "aws")
    working_dir = terraform_config.get("working_directory", "terraform")
    workspaces = terraform_config.get("workspaces")
    proj = project_name or terraform_config.get("project_name", "")

    job_yaml = _terraform_ci_job(
        provider=provider,
        working_directory=working_dir,
        workspaces=workspaces,
    )

    wf_name = f"{proj} Terraform" if proj else "Terraform"

    header = f"""\
# Generated by DevOps Control Plane
name: {wf_name}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
"""
    content = header + job_yaml

    return GeneratedFile(
        path=".github/workflows/terraform.yml",
        content=content,
        overwrite=False,
        reason=f"Terraform CI workflow ({provider} provider)",
    )
